spring.profiles.active: local

spring:
  application:
    name: gateway-service
  config:
    import:
      - gateway.yml
      - swagger.yml
      - auth.yml
      - eureka.yml

server:
  port: ${APPLICATION_PORT:8080}
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100
  domain:
    user: ${FLEX_USER_SERVICE_DOMAIN:http://127.0.0.1:8081}
    service: ${FLEX_SERVICE_DOMAIN:http://127.0.0.1:8080} # TODO: to be modified

logging:
  level:
    root: INFO
    codeping.flex.gateway.security.filter.AccessTokenFilter: TRACE
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG

---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: prod

