spring.profiles.active: local

spring:
  config:
    import:
      - gateway.yml
      - swagger.yml

server:
  port: ${APPLICATION_PORT:8080}
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

---
spring.config.activate.on-profile: local


---
spring.config.activate.on-profile: dev



---
spring.config.activate.on-profile: prod

