spring.profiles.active: local

spring:
  application:
    name: gateway-service
  config:
    import:
      - gateway.yml
      - swagger.yml
      - auth.yml

server:
  port: ${APPLICATION_PORT:8080}
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100

logging:
  level:
    root: INFO
    codeping.flex.gateway.security.filter.AccessTokenFilter: TRACE
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG

---
spring.config.activate.on-profile: local
spring:
  config:
    import:
      - eureka.yml
      - env.properties
  cloud:
    kubernetes:
      config:
        enabled: false
logging:
  level:
    root: INFO
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG


---

spring.config.activate.on-profile: dev
spring:
  config:
    import:
      - eureka.yml
  cloud:
    kubernetes:
      config:
        enabled: false
logging:
  level:
    root: INFO
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG

---

spring.config.activate.on-profile: prod

spring:
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true

eureka:
  client:
    enabled: false
  instance:
    prefer-ip-address: true
  discovery:
    enabled: false

