---
spring.config.activate.on-profile: local

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**, /api/users/**, /api/follow/**, /api/user-service/**
        - id: blog-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/blogs/**, /api/posts/**, /api/blog-service/**
        - id: investment-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/investments/**, /api/investment-service/**
        - id: stock-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/stocks/**, /api/stock-service/**

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: prod