---
spring.config.activate.on-profile: local

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**, /api/users/**, /api/follow/**, /api/user-service/**
        - id: blog-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/blogs/**, /api/posts/**, /api/blog-service/**
        - id: investment-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/investments/**, /api/investment-service/**
        - id: stock-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/stocks/**, /api/stock-service/**
        - id: image-service
          uri: http://loacalhost:8085
          predicates:
            - Path=/api/presigned-url/**, /api/image-service/**
        - id: ai-news-service
          uri: http://loacalhost:8086
          predicates:
            - Path=/api/news-summary/**, /api/ai-news-service/**
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true

---
spring.config.activate.on-profile: dev
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: user-service
          uri: http://user-service
          predicates:
            - Path=/api/auth/**, /api/users/**, /api/follow/**, /api/user-service/**
        - id: blog-service
          uri: http://blog-service
          predicates:
            - Path=/api/blogs/**, /api/posts/**, /api/blog-service/**
        - id: investment-service
          uri: http://investment-service
          predicates:
            - Path=/api/investments/**, /api/investment-service/**
        - id: stock-service
          uri: http://stock-service
          predicates:
            - Path=/api/stocks/**, /api/stock-service/**
        - id: image-service
          uri: http://image-service
          predicates:
            - Path=/api/presigned-url/**, /api/image-service/**
        - id: ai-news-service
          uri: http://ai-news-service
          predicates:
            - Path=/api/news-summary/**, /api/ai-news-service/**
---
spring.config.activate.on-profile: prod